force-app/main/default/objects/Commitment_History__c/Commitment_History__c.object-meta.xml
<CustomObject>
    <label>Commitment</label>
    <nameField>
        <displayFormat>COMMIT-{000000}</displayFormat>
        <label>Commit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commitments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commitment_History__c/fields/Amount_Sign__c.field-meta.xml
<CustomField>
    <fullName>Amount_Sign__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commitment_History__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Commit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Commitment_History__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipName>Commitment_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Commitment_History__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bankruptcy</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commitment_History__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Decommitment</fullName>
            </value>
            <value>
                <fullName>Recommitment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Approved Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Date__c</fullName>
    <label>Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vehicle Purchase</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Debt Management</fullName>
            </value>
            <value>
                <fullName>Vacation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Refinanced__c.field-meta.xml
<CustomField>
    <fullName>Refinanced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Refinanced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Total_Transferred__c.field-meta.xml
<CustomField>
    <fullName>Total_Transferred__c</fullName>
    <label>Total Transferred</label>
    <summarizedField>Loan_Transaction__c.Total_Debit__c</summarizedField>
    <summaryFilterItems>
        <field>Loan_Transaction__c.Type__c</field>
        <operation>equals</operation>
        <value>Transfer</value>
    </summaryFilterItems>
    <summaryForeignKey>Loan_Transaction__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/CommitmentHistoryController.cls
public class CommitmentHistoryController implements IController{
@AuraEnabled
    public static List<SObject> getAll(){
        return [SELECT
                    Name, Amount__c, Reason__c, Loan__c, Date__c, Type__c, Amount_Sign__c
                FROM Commitment_History__c
                ORDER BY CreatedDate DESC
                LIMIT 1000];                         
    }

    @AuraEnabled
    public static List<SObject> getAll(SObject value) {
        return getAll(value, null);
    }
    public static List<SObject> getAll(SObject value,String autoNumber){
        Commitment_History__c param = (Commitment_History__c)value;
        String queryString = 'Select Name, Amount__c, Reason__c, Loan__c, Date__c, Type__c, Amount_Sign__c'+
                        'Total_Transferred__c,Maturity_Date__c,Refinanced__c from Commitment_History__c where';

        if(!string.isBlank(autoNumber)){
            queryString += ' Name = \'' + String.escapeSingleQuotes(autoNumber) +  '\' AND';
        }
        if(param.Amount__c  != Null){
            queryString += ' Amount__c = '+ param.Amount__c +' AND';
        }
        
        if (!string.isBlank(param.Loan__c)) {
            queryString += ' Loan__c = \'' + String.escapeSingleQuotes(param.Loan__c) + '\' AND';
        }
        if (param.Date__c != Null) {
            queryString += ' Date__c = '+ param.Date__c +' AND';
        }        
        if (!string.isBlank(param.Type__c)) {
            queryString += ' Type__c = \'' + String.escapeSingleQuotes(param.Type__c) + '\' AND';
        }

        if (!string.isBlank(param.Reason__c)) {
            queryString += ' Reason__c = \'' + String.escapeSingleQuotes(param.Reason__c) + '\' AND';
        }

        queryString = queryString.removeEnd(' AND');
		List<SObject> entities=Database.query(queryString);
        return entities;
    }

    @AuraEnabled
    public static SObject getById(Id id){
        SObject entity = [SELECT
                            Name, Amount__c, Reason__c, Loan__c, Date__c, Type__c, Amount_Sign__c 
                        FROM Commitment_History__c
                        WHERE Id=:id];
        return entity; 
    }

    public Id create(SObject value) {
        Commitment_History__c entity = (Commitment_History__c)value;
        return entity.Id;
    }

    public Boolean createMany(List<SObject> values) {
        List<Commitment_History__c> entities = (List<Commitment_History__c>)values;
        insert entities;
        return true;
    }

    public Boolean edit(SObject value) {
        Commitment_History__c entity = (Commitment_History__c)value;
        update entity;
        return true;
    }

    public Boolean editMany(List<SObject> values) {
        List<Commitment_History__c> entities = (List<Commitment_History__c>)values;
        update entities;
        return true;
    }

    @AuraEnabled
    public static Boolean remove(Id id) {
        Commitment_History__c entity = [SELECT Id FROM Commitment_History__c WHERE Id=:id];
        delete entity; 
        return true;
    }
    
    @AuraEnabled
    public static List<SObject> getAllByLimit(Id id){
        List<sObject> entities=[SELECT
                      Name,Amount__c, Reason__c, Loan__c, Date__c, Type__c, Amount_Sign__c
                 FROM Commitment_History__c
                 WHERE Loan__c = :id
                 ORDER BY Id DESC
                 LIMIT :7]; 
        return entities;
    }
}