force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Application Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Approved_Amount__c.field-meta.xml
<CustomField>
    <fullName>Approved_Amount__c</fullName>
    <label>Approved Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Cancel_date__c.field-meta.xml
<CustomField>
    <fullName>Cancel_date__c</fullName>
    <label>Cancelled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Cancel_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Cancel_user__c.field-meta.xml
<CustomField>
    <fullName>Cancel_user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Completion_Status__c.field-meta.xml
<CustomField>
    <fullName>Completion_Status__c</fullName>
    <label>Completion Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
                <isActive>false</isActive>
                <label>Withdrawn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestApplicationController.cls
@IsTest
private with sharing class TestApplicationController {
static IController controller = new ApplicationController();
    static ApplicationController ctrl = new ApplicationController();
    static SampleDataObjects dataSet = new SampleDataObjects();

    static Application__c app = new Application__c();
    static List<Application__c> appList = new List<Application__c>();
    
    static Date d = date.today();
	
    @IsTest
    static void testCreate(){
        app =(Application__c) dataSet.CreateApplication('Contact','Simple');
        System.assertNotEquals(null, app.Id);
    }
    
    @IsTest
    static void testCreateMany(){

        boolean isTrue = controller.createMany(null);
        System.assertNotEquals(false, isTrue);
    }

    @IsTest
    static void testEdit(){
        app =(Application__c) dataSet.CreateApplication('Contact','Simple');
        app.Status__c = 'Complete';
        app.Completion_Status__c = 'Canceled';
        app.Cancel_date__c = d;
        app.Cancel_user__c = UserInfo.getUserId();
        app.Cancel_Reason__c = 'Declined';
        boolean isTrue = controller.edit(app);
        System.assertNotEquals(false, isTrue);
    }

    @IsTest
    static void testEditMany(){
        app =(Application__c) dataSet.CreateGrantApplication('Contact');
        app.Status__c = 'Complete';
        app.Completion_Status__c = 'Approved';
        app.Approved_Amount__c = 900;
        app.Approved_Date__c = d;
        
        appList.add(app);
        
        boolean isTrue = controller.editMany(appList);
        System.assertNotEquals(false, isTrue);
    }
    
    @IsTest
    static void basicValidationContact(){
        app =(Application__c) dataSet.CreateApplication('Contact','Simple');
        app.Amount__c = 23423233;
        app.Term__c = 90;
        try{
            update app;
        }
        catch(Exception e){
            
        }
    }
    
    @IsTest
    static void basicValidationAccount(){
        app =(Application__c) dataSet.CreateApplication('Account','Simple');
        app.RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get('Business Loan').getRecordTypeId();
        app.Amount__c = 23423233;
        app.Term__c = 90;
        try{
            update app;
        }
        catch(Exception e){
            
        }
    }
    
    @IsTest
    static void grantValidation(){
        app =(Application__c) dataSet.CreateGrantApplication('Contact');
        app.Amount__c = 1200000;
        try{
            update app;
        }
        catch(Exception e){
            
        }
    }
    
    @IsTest
    static void cancelValidation(){

        app =(Application__c) dataSet.CreateApplication('Contact','Simple');
        app.Status__c = 'Complete';
        app.Completion_Status__c = 'Canceled';
        app.Cancel_date__c = d.addDays(-2);
        try{
            update app;
        }
        catch(Exception e){
            
        }
    }
    
    @IsTest
    static void approveValidation(){
        app =(Application__c) dataSet.CreateApplication('Contact','Simple');
        app.Status__c = 'Complete';
        app.Completion_Status__c = 'Approved';
        app.Approved_Amount__c = 23234322;
        app.Approved_Date__c = d.addDays(-2);
        try{
            update app;
        }
        catch(Exception e){
            
        }
    }

    @IsTest
    static void testGetById(){
		app = (Application__c) dataSet.CreateApplication('Contact','Simple');
        Application__c app = (Application__c)controller.getById(app.Id);
        System.assertNotEquals(null, app);

    }

    @IsTest
    static void testGetAll(){
        Integer resultlength;
        app =(Application__c) dataSet.CreateApplication('Contact','Simple');
        
        appList = (List<Application__c>)ApplicationController.getAll(null);
        System.assertEquals(null, appList);
        
        appList = (List<Application__c>)ApplicationController.getAll();
        System.assertNotEquals(null, appList);

        appList = (List<Application__c>)ApplicationController.getSource();
        System.assertEquals(true,appList.size()>0);

    }

    @IsTest
    static void testRemove(){
        app = (Application__c) dataSet.CreateApplication('Contact','Simple');
        boolean isTrue = controller.remove(app.Id);
        System.assertEquals(true, isTrue);
    }

}