force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Application Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collateral__c/Collateral__c.object-meta.xml
<CustomObject>
    <description>Collateral refers to the different kinds of assets that Contacts pledge as security for a loan.</description>
    <label>Collateral</label>
    <nameField>
        <displayFormat>COL-{000000}</displayFormat>
        <label>Collateral Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collateral__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Collaterals</relationshipLabel>
    <relationshipName>Collaterals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Collateral__c/fields/Collateral_Type__c.field-meta.xml
<CustomField>
    <fullName>Collateral_Type__c</fullName>
    <label>Collateral Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Housing/Mortgage</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Promissory Note</fullName>
            </value>
            <value>
                <fullName>GSA</fullName>
            </value>
            <value>
                <fullName>PPSA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collateral__c/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestCollateralController.cls
@IsTest
private with sharing class TestCollateralController {
static IController controller = new CollateralController();
    static ICollateral iCtrl = new CollateralController();
    static Collateral__c col = new Collateral__c();

    static void create(){
        Date d = date.today();
        Application__c app = new Application__c();
        Contact con = new Contact(LastName= 'Sam');
        insert con;
        
        id recId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get('Personal Line of Credit').getRecordTypeId();
        
        app.RecordTypeId = recId;
        app.Contact__c = con.Id;
        app.Amount__c = 25000;
        app.Application_Date__c = date.today();
        app.Status__c = 'New';
        insert app; 
        
        col.Application__c = app.Id;
        col.Amount__c = 2900;
        col.Collateral_Type__c = 'Other';
        col.Issue_Date__c = d.addDays(-4);
        col.Expiration_Date__c = d.addDays(-2);
        insert col;
    }
    
        
    @IsTest
    static void setExpired(){
        create(); 
        Boolean t = CollateralController.setExpired();
        System.assertEquals(true, t);
    }
  
    @IsTest
    static void testCreate(){
        Id Id = controller.create(col);
        System.assertEquals(null, Id);
    }
    
    @IsTest
    static void testCreateMany(){
        boolean isTrue = controller.createMany(null);
        System.assertNotEquals(false, isTrue);
    }

    @IsTest
    static void testEdit(){
        boolean isTrue = controller.edit(col);
        System.assertNotEquals(false, isTrue);
    }

    @IsTest
    static void testEditMany(){

        create();

        col.Collateral_Type__c = 'Insurance';
        List<Collateral__c> listCol = new List<Collateral__c>(); 
        listCol.add(col);

        boolean isTrue = controller.editMany(listCol);
        System.assertNotEquals(false, isTrue);
    }

    @IsTest
    static void testGetById(){

        Collateral__c col = (Collateral__c)controller.getById(col.Id);
        System.assertEquals(null, col);

    }

    @IsTest
    static void testGetAll(){
        List<Collateral__c> cols = (List<Collateral__c>)CollateralController.getAll(col);
        System.assertEquals(null, cols);

    }
    
    @IsTest
    static void testGetAllEmpty(){
        List<Collateral__c> cols = (List<Collateral__c>)CollateralController.getAll();
        System.assertEquals(null, cols);

    }
 

    @IsTest
    static void testRemove(){
        boolean isTrue = controller.remove(col.id);
        System.assertEquals(true, isTrue);
    }
}