force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Application Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collateral__c/Collateral__c.object-meta.xml
<CustomObject>
    <description>Collateral refers to the different kinds of assets that Contacts pledge as security for a loan.</description>
    <label>Collateral</label>
    <nameField>
        <displayFormat>COL-{000000}</displayFormat>
        <label>Collateral Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collateral__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Collaterals</relationshipLabel>
    <relationshipName>Collaterals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Collateral__c/fields/Collateral_Type__c.field-meta.xml
<CustomField>
    <fullName>Collateral_Type__c</fullName>
    <label>Collateral Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Housing/Mortgage</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Promissory Note</fullName>
            </value>
            <value>
                <fullName>GSA</fullName>
            </value>
            <value>
                <fullName>PPSA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collateral__c/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_picture_id__c.field-meta.xml
<CustomField>
    <fullName>Profile_picture_id__c</fullName>
    <label>Profile Picture Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestCustomProfilePictureController.cls
@IsTest
private with sharing class TestCustomProfilePictureController {
	static customProfilePictureController ctrl; //= new customProfilePictureController();
    static Contact con = new Contact();
    static Application__c app = new Application__c();
    static Collateral__c col = new Collateral__c();
    
    static void createContact(){
        con.LastName = 'Contact 1';
        con.Profile_picture_id__c = 'sample';
        insert con;
    }
    
    static void createApplication(){
        createContact();
        
        id recId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get('Personal Line of Credit').getRecordTypeId();
        
        app.RecordTypeId = recId;
        app.Contact__c = con.Id;
        app.Amount__c = 25000;
        app.Application_Date__c = date.today();
        app.Status__c = 'New';
        insert app; 
    }
    
    static void createCollateral(){
        createApplication();
        
        col = new Collateral__c();
        col.Application__c = app.Id;
        col.Issue_Date__c = date.toDay();
        col.Collateral_Type__c = 'Other';
        col.Picture_Id__c = 'sample';
        insert col;
    }
    
    @IsTest
    static void updateProfilePictureId(){
        createContact();
        string a = customProfilePictureController.updateProfilePictureId(con.Id,'documentId','Contact');
        system.assertNotEquals(null, a);
    }
    
    @IsTest
    static void updateProfilePictureIdCol(){
        createCollateral();
        string a = customProfilePictureController.updateProfilePictureId(col.Id,'documentId','Collateral__c');
        system.assertNotEquals(null, a);
    }
    
    @IsTest
    static void getProfilePictureId(){
        createCollateral();
        
        string a = customProfilePictureController.getProfilePictureId(col.Id,'Collateral__c');
        system.assertEquals('sample', a);
    }
    
    @IsTest
    static void getProfilePictureIdContact(){
        createContact();
        
        string a = customProfilePictureController.getProfilePictureId(con.Id,'Contact');
        system.assertEquals('sample', a);
    }
    
     @IsTest
    static void getPlaceholderUrl(){
        string a = customProfilePictureController.getPlaceholderUrl('Collateral__c');
        system.assertNotEquals(null, a);
    }
}