force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Application Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Balloon_Amount__c.field-meta.xml
<CustomField>
    <fullName>Balloon_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Balloon Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Completion_Status__c.field-meta.xml
<CustomField>
    <fullName>Completion_Status__c</fullName>
    <label>Completion Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
                <isActive>false</isActive>
                <label>Declined</label>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
                <isActive>false</isActive>
                <label>Withdrawn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Day_Count__c.field-meta.xml
<CustomField>
    <fullName>Day_Count__c</fullName>
    <formula>IF(!ISBLANK( Loan_Product__c ),  TEXT( Loan_Product__r.Day_Count__c ),&apos;&apos;  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Day Count</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Disbursal_Date__c.field-meta.xml
<CustomField>
    <fullName>Disbursal_Date__c</fullName>
    <label>Disbursal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Final_Rate__c.field-meta.xml
<CustomField>
    <fullName>Final_Rate__c</fullName>
    <formula>IF(ISNULL(Loan_Product__r.Interest_Product__r.Current_Rate__c),Rate__c,(Loan_Product__r.Interest_Product__r.Current_Rate__c+Rate__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fixed Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Initial_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Payment_Date__c</fullName>
    <label>Initial Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Interest_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Interest_Calculation_Method__c</fullName>
    <formula>IF(!ISBLANK( Loan_Product__c ),  TEXT(Loan_Product__r.Interest_Calculation_Method__c)   ,&apos;&apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Calculation Method</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Interest_Compounding_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Interest_Compounding_Frequency__c</fullName>
    <formula>IF(! ISBLANK( Loan_Product__c),  TEXT( Loan_Product__r.Interest_Compounding_Frequency__c ), &apos;&apos;  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Compounding Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Product</label>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Pay_Seasonal_Interest__c.field-meta.xml
<CustomField>
    <fullName>Pay_Seasonal_Interest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pay Seasonal Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Periods_Deferred_with_Grace__c.field-meta.xml
<CustomField>
    <fullName>Periods_Deferred_with_Grace__c</fullName>
    <label>Periods Deferred With Grace</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Total Rate</label>
    <precision>9</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Loan Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vehicle Purchase</fullName>
            </value>
            <value>
                <fullName>Home Improvement</fullName>
            </value>
            <value>
                <fullName>Debt Management</fullName>
            </value>
            <value>
                <fullName>Vacation</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Repayment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency__c</fullName>
    <label>Repayment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Repeat_Seasonal_Periods__c.field-meta.xml
<CustomField>
    <fullName>Repeat_Seasonal_Periods__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Repeat Seasonal Periods</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Seasonal_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Seasonal_Payment_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Seasonal Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Seasonal_Periods__c.field-meta.xml
<CustomField>
    <fullName>Seasonal_Periods__c</fullName>
    <label>Seasonal Periods Without Payment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/Loan_Product__c.object-meta.xml
<CustomObject>
    <description>Represents an offered lending product</description>
    <label>Loan Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Product__c/fields/Day_Count__c.field-meta.xml
<CustomField>
    <fullName>Day_Count__c</fullName>
    <description>The method of calculating the number of days in month and year</description>
    <label>Day Count</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actual / Actual</fullName>
                <default>true</default>
                <label>Actual / Actual</label>
            </value>
            <value>
                <fullName>Actual / 365</fullName>
            </value>
            <value>
                <fullName>Actual / 365.25</fullName>
            </value>
            <value>
                <fullName>Actual / 360</fullName>
            </value>
            <value>
                <fullName>30 / 360</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Interest_Calculation_Method__c</fullName>
    <label>Interest Calculation Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Simple</fullName>
                <default>true</default>
                <label>Simple</label>
            </value>
            <value>
                <fullName>Compound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Compounding_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Interest_Compounding_Frequency__c</fullName>
    <label>Interest Compounding Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Interest_Calculation_Method__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/classes/ApplicationController.cls
public with sharing class ApplicationController implements IController {
    @AuraEnabled
    public static List<SObject> getAll(){
        List<SObject> applications = [Select Name,Amount__c, 
                        Approved_Date__c,Contact__c,CreatedById,Rate__c,
                        LastModifiedById,OwnerId,Loan_Product__c,Reason__c,Repayment_Frequency__c,Status__c,
                        Term__c,Initial_Payment_Date__c, Completion_Status__c from Application__c ORDER BY CreatedDate DESC LIMIT 1000];
        return applications;                        
    }

     @AuraEnabled
    public static List<SObject> getAll(SObject value) {
        return getAll(value, null);
    }

    public static List<SObject> getAll(SObject value,String autoNumber){
        /* Application__c param;
        if(value == null)
            param = new Application__c();
        else
            param = (Application__c)value;
        String queryString = 'Select Name, Amount__c, Account__r.Name, LastModifiedById, OwnerId, Application_Date__c,'+
                        'Contact__r.Name, Approved_Date__c, Reason__c, Repayment_Frequency__c, Source__c, Status__c,'+
                         'Term__c, Initial_Payment_Date__c, Loan_Product__c, Completion_Status__c from Application__c where';
                   
        if(!string.isBlank(autoNumber)){
            queryString += ' Name = \'' + String.escapeSingleQuotes(autoNumber) +  '\' AND';
        }
         if(!string.isBlank(param.Contact__c)){
            queryString += ' Contact__c = \'' + String.escapeSingleQuotes(param.Contact__c) +  '\' AND';
        }
          if(!string.isBlank(param.Account__c)){
            queryString += ' Account__c = \'' + String.escapeSingleQuotes(param.Account__c) +  '\' AND';
        }
          if(!string.isBlank(param.CreatedById)){
            queryString += ' CreatedById = \'' + String.escapeSingleQuotes(param.CreatedById) +  '\' AND';
        }
        if(!string.isBlank(param.LastModifiedById)){
            queryString += ' LastModifiedById = \'' + String.escapeSingleQuotes(param.LastModifiedById) +  '\' AND';
        }
        if(!string.isBlank(param.OwnerId)){
            queryString += ' OwnerId = \'' + String.escapeSingleQuotes(param.OwnerId) +  '\' AND';
        }
        if(!string.isBlank(param.Loan_Product__c)){
            queryString += ' Loan_Product__c = \'' + String.escapeSingleQuotes(param.Loan_Product__c) +  '\' AND';
        }
         if(!string.isBlank(param.Reason__c)){
            queryString += ' Reason__c = \'' + String.escapeSingleQuotes(param.Reason__c) +  '\' AND';
        }
         if(!string.isBlank(param.Repayment_Frequency__c)){
            queryString += ' Repayment_Frequency__c = \'' + String.escapeSingleQuotes(param.Repayment_Frequency__c) +  '\' AND';
        }
         if(!string.isBlank(param.Status__c)){
            queryString += ' Status__c = \'' + String.escapeSingleQuotes(param.Status__c) +  '\' AND';
        }
         if(!string.isBlank(param.Source__c))
         {
            queryString += ' Source__c = \'' + String.escapeSingleQuotes(param.Source__c) +  '\' AND';
        }
        if(param.Amount__c  != Null){
            queryString += ' Amount__c = '+ param.Amount__c +' AND';
        }
        if(param.Term__c  != Null){
            queryString += ' Term__c = '+ param.Term__c +' AND';
        }
        if(param.Approved_Date__c != Null){       
            String formatedDate = DateUtility.formatDateTime(param.Approved_Date__c, 'yyyy-MM-dd\'T\'hh:mm:ss\'Z\' AND');
            queryString += ' Approved_Date__c = '+ formatedDate +' AND';
        }
        if(param.Initial_Payment_Date__c != Null)
        {
            String formatedDate = DateUtility.formatDateTime(param.Initial_Payment_Date__c, 'yyyy-MM-dd\'T\'hh:mm:ss\'Z\' AND');
            queryString += 'Initial_Payment_Date__c = ' + formatedDate +' AND';
        }
        queryString = queryString.removeEnd(' AND');
        queryString = queryString.removeEnd(' where');
        List<SObject> application = Database.query(queryString);
        System.debug(application); */
        return null;// application;
    }
    @AuraEnabled
    public static SObject getById(Id id){

        SObject application = [Select Name,Amount__c,
                                    Approved_Date__c,Contact__c,CreatedById,Rate__c,Final_Rate__c,Completion_Status__c,RecordType.Name,Account__r.Name,
                                    LastModifiedById,OwnerId,Loan_Product__c,Reason__c,Repayment_Frequency__c,Status__c,Disbursal_Date__c,recordTypeId,
                                    Account__r.ShippingStreet,Account__r.ShippingCity,Account__r.ShippingState,Account__r.ShippingCountry,
                               		Account__r.ShippingPostalCode, Contact__r.Name,Contact__r.MailingStreet,Contact__r.MailingCity,
                               		Contact__r.MailingState,Contact__r.MailingCountry,Contact__r.MailingPostalCode, Term__c, Periods_Deferred_with_Grace__c,
                               		Balloon_Amount__c,Seasonal_Payment_Amount__c,Pay_Seasonal_Interest__c,Repeat_Seasonal_Periods__c,
                                    Seasonal_Periods__c,Loan_Product__r.Interest_Calculation_Method__c,Loan_Product__r.Day_Count__c,
                                    Loan_Product__r.Interest_Compounding_Frequency__c,Initial_Payment_Date__c from Application__c
                               where id=:id]; 
        
        
        return application; 
    }
   @AuraEnabled
    public static List<SObject> getSource(){
        List<SObject> applications = [Select Name,Amount__c,
                                        Approved_Date__c,Contact__r.Name,CreatedById,Rate__c,
                                        LastModifiedById,OwnerId,Loan_Product__c,Reason__c,Application_Date__c,Repayment_Frequency__c,Status__c,
                                        Term__c,Initial_Payment_Date__c, Completion_Status__c from Application__c 
                                      where Status__c != 'Complete' AND Source__c='Online' 
                                      ORDER BY CreatedDate DESC LIMIT 1000];
        return applications;                       
    }
    @AuraEnabled
    public static Id create(SObject value){
        Application__c application =  (Application__c)value;
        application.Status__c='New';
        if(application.RecordTypeId == null){
            application.RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get('Personal Loan').getRecordTypeId();     
        }
        insert application;
        return application.id;
    }

    public Boolean createMany(List<SObject> values){
       // List<Application__c> applications =  (List<Application__c>)values;
       // insert applications;
        return true;
    }
    public Boolean edit(SObject value){
        Application__c application =  (Application__c)value;
        update application;
        return true;
    }

    @AuraEnabled
    public static Boolean editMany(List<SObject> values){
        List<Application__c> applications =  (List<Application__c>)values;
        update applications;
        return true;
    }
    public static Boolean remove(Id id){
       // Application__c application = [Select Id from Application__c where id=:id];
      //  delete application; 
        return true;
    }
}