force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Application Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Collateral__c/Collateral__c.object-meta.xml
<CustomObject>
    <description>Collateral refers to the different kinds of assets that Contacts pledge as security for a loan.</description>
    <label>Collateral</label>
    <nameField>
        <displayFormat>COL-{000000}</displayFormat>
        <label>Collateral Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Collateral__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Collaterals</relationshipLabel>
    <relationshipName>Collaterals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Collateral__c/fields/Collateral_Type__c.field-meta.xml
<CustomField>
    <fullName>Collateral_Type__c</fullName>
    <label>Collateral Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Housing/Mortgage</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Promissory Note</fullName>
            </value>
            <value>
                <fullName>GSA</fullName>
            </value>
            <value>
                <fullName>PPSA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Collateral__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Collateral__c/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Collateral__c/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <label>Reference Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CollateralController.cls
public with sharing class CollateralController implements IController, ICollateral, iprofilePicture{
    public static Boolean setExpired(){
        IController col=new CollateralController();
        Date dt=Date.today();
        List<Collateral__c> uobj=new List<Collateral__c>();
        List<Collateral__c> cobj=[select Expired__c from Collateral__c where Expiration_Date__c <:dt];
        for(Collateral__c obj:cobj){
            obj.Expired__c=true;
            uobj.add(obj);
        }
        col.editMany(uobj);
        return true;
    }
    
    public static List<SObject> getAll(){
        //List<SObject> entity= [Select Application__c,Collateral_Type__c,Expiration_Date__c,Expired__c,Issue_Date__c,Reference_Number__c,	Amount__c,CreatedById from Collateral__c ORDER BY CreatedDate DESC LIMIT 1000];
        return null; // entity;                        
    }
    public static List<SObject> getAll(SObject Amount){
        return getAll(Amount,null);
    }

    public static List<SObject> getAll(SObject Amount,String autoNumber){
        /*Collateral__c param;
        if(Amount == null){
            param = new Collateral__c();
        }else{
             param = (Collateral__c)Amount;
        }
        String queryString; = 'Select Application__c,Collateral_Type__c,Expiration_Date__c,Expired__c,Issue_Date__c,Reference_Number__c,	Amount__c,CreatedById from Collateral__c where';
        
        if(!string.isBlank(autoNumber)){
            queryString +=' Name = \'' + String.escapeSingleQuotes(param.Name) +  '\' AND';
        }
        if(param.Amount__c  != Null){
            queryString += 'Amount__c = '+ param.Amount__c +' AND';
        }
        if(!string.isBlank(param.Application__c)){
            queryString += ' Application__c = \'' + String.escapeSingleQuotes(param.Application__c) +  '\' AND';
        }
        if(!string.isBlank(param.Collateral_Type__c)){
            queryString += ' Collateral_Type__c = \'' + String.escapeSingleQuotes(param.Collateral_Type__c) +  '\' AND';
        }
        if(param.Expiration_Date__c!=Null){
            String formatedDate = DateUtility.formatDateTime(param.Expiration_Date__c, 'yyyy-MM-dd');
            queryString += ' Expiration_Date__c = ' + formatedDate +  ' AND';
        }
        if(param.Expired__c!=Null){
            queryString += ' Expired__c = ' +param.Expired__c +  ' AND';
        }

        queryString = queryString.removeEnd(' AND');
        queryString = queryString.removeEnd(' where');
        List<SObject> entity = Database.query(queryString);
        System.debug(entity);*/

        return null; // entity;
    }

    public SObject getById(Id id){
        //SObject entity = [Select Application__c,Collateral_Type__c,Expiration_Date__c,Expired__c,Issue_Date__c,Reference_Number__c,Amount__c,CreatedById from Collateral__c where id=:id];
        return null; // entity; 
    }

    public Id create(SObject Amount	){
        //Collateral__c entity =  (Collateral__c)Amount;
        //insert entity;
        return null;//entity.id;
    }

    public Boolean createMany(List<SObject> Amount){
        //List<Collateral__c> entity=  (List<Collateral__c>)Amount;
        //insert entity;
        return true;
    }
    public Boolean edit(SObject Amount){
        //Collateral__c entity =  (Collateral__c)Amount;
        //update entity;
        return true;
    }

    public Boolean editMany(List<SObject> Amount){
        List<Collateral__c> entity=  (List<Collateral__c>)Amount;
        update entity;
        return true;
    }
    public Boolean remove(Id id){
        //Collateral__c entity = [Select Id from Collateral__c where id=:id];
        //delete entity; 
        return true;
    }
  public String  updateProfilePictureId(Id id, String documentId) { // covered in customprofile picture test
            //Collateral__c collateral=[ Select Id,Picture_Id__c from Collateral__c where  Id=:id ];
            //collateral.Picture_Id__c = documentId;
            //update collateral;
            return documentId;       
    }

    public String getProfilePictureId(Id id){ // covered in customprofile picture test
            Collateral__c collateral=[ Select Picture_Id__c from Collateral__c where  Id=:id ];
            return collateral.Picture_Id__c;   
    }
}