force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Application Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Balloon_Amount__c.field-meta.xml
<CustomField>
    <fullName>Balloon_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Balloon Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Day_Count__c.field-meta.xml
<CustomField>
    <fullName>Day_Count__c</fullName>
    <formula>IF(!ISBLANK( Loan_Product__c ),  TEXT( Loan_Product__r.Day_Count__c ),&apos;&apos;  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Day Count</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Disbursal_Date__c.field-meta.xml
<CustomField>
    <fullName>Disbursal_Date__c</fullName>
    <label>Disbursal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Final_Rate__c.field-meta.xml
<CustomField>
    <fullName>Final_Rate__c</fullName>
    <formula>IF(ISNULL(Loan_Product__r.Interest_Product__r.Current_Rate__c),Rate__c,(Loan_Product__r.Interest_Product__r.Current_Rate__c+Rate__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fixed Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Initial_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Payment_Date__c</fullName>
    <label>Initial Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Interest_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Interest_Calculation_Method__c</fullName>
    <formula>IF(!ISBLANK( Loan_Product__c ),  TEXT(Loan_Product__r.Interest_Calculation_Method__c)   ,&apos;&apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Calculation Method</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Interest_Compounding_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Interest_Compounding_Frequency__c</fullName>
    <formula>IF(! ISBLANK( Loan_Product__c),  TEXT( Loan_Product__r.Interest_Compounding_Frequency__c ), &apos;&apos;  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Compounding Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Product</label>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Pay_Seasonal_Interest__c.field-meta.xml
<CustomField>
    <fullName>Pay_Seasonal_Interest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pay Seasonal Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Periods_Deferred_with_Grace__c.field-meta.xml
<CustomField>
    <fullName>Periods_Deferred_with_Grace__c</fullName>
    <label>Periods Deferred With Grace</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Repayment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Frequency__c</fullName>
    <label>Repayment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Repeat_Seasonal_Periods__c.field-meta.xml
<CustomField>
    <fullName>Repeat_Seasonal_Periods__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Repeat Seasonal Periods</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Seasonal_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Seasonal_Payment_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Seasonal Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Seasonal_Periods__c.field-meta.xml
<CustomField>
    <fullName>Seasonal_Periods__c</fullName>
    <label>Seasonal Periods Without Payment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Approved Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Loan</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Day_Count__c.field-meta.xml
<CustomField>
    <fullName>Day_Count__c</fullName>
    <formula>Application__r.Day_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Day Count</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Interest_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Interest_Calculation_Method__c</fullName>
    <formula>Application__r.Interest_Calculation_Method__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Calculation Method</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Interest_Compounding_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Interest_Compounding_Frequency__c</fullName>
    <formula>Application__r.Interest_Compounding_Frequency__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Compounding Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Loan_Product__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Loan Product</label>
    <referenceTo>Loan_Product__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/Loan_Product__c.object-meta.xml
<CustomObject>
    <description>Represents an offered lending product</description>
    <label>Loan Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Product__c/fields/Day_Count__c.field-meta.xml
<CustomField>
    <fullName>Day_Count__c</fullName>
    <description>The method of calculating the number of days in month and year</description>
    <label>Day Count</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actual / Actual</fullName>
                <default>true</default>
                <label>Actual / Actual</label>
            </value>
            <value>
                <fullName>Actual / 365</fullName>
            </value>
            <value>
                <fullName>Actual / 365.25</fullName>
            </value>
            <value>
                <fullName>Actual / 360</fullName>
            </value>
            <value>
                <fullName>30 / 360</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Interest_Calculation_Method__c</fullName>
    <label>Interest Calculation Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Simple</fullName>
                <default>true</default>
                <label>Simple</label>
            </value>
            <value>
                <fullName>Compound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Compounding_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Interest_Compounding_Frequency__c</fullName>
    <label>Interest Compounding Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Interest_Calculation_Method__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheduled_Transaction__c/Scheduled_Transaction__c.object-meta.xml
<CustomObject>
    <label>Scheduled Transaction</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Loan Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>IF(ISNULL(Principal__c),0,Principal__c)+ IF(ISNULL(Fees__c),0,Fees__c) +  IF(ISNULL(Interest__c),0,Interest__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scheduled_Transaction__c/fields/Fees__c.field-meta.xml
<CustomField>
    <fullName>Fees__c</fullName>
    <label>Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scheduled_Transaction__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Scheduled Transactions</relationshipLabel>
    <relationshipName>Scheduled_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Transaction__c/fields/Payment_Number__c.field-meta.xml
<CustomField>
    <fullName>Payment_Number__c</fullName>
    <label>Payment Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scheduled_Transaction__c/fields/Remaining_Balance__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Balance__c</fullName>
    <label>Remaining Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scheduled_Transaction__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <label>Scheduled Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Scheduled_Transaction__c/fields/Total_Payment__c.field-meta.xml
<CustomField>
    <fullName>Total_Payment__c</fullName>
    <label>Total Payment</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scheduled_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disbursal</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Balloon</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoanAppScheduleController.cls
public class LoanAppScheduleController {

    public List<Scheduled_Transaction__c> scheduledTransactions {get;set;}
    public Application__c app {get;set;}

    public LoanAppScheduleController() {
        IController applicationCtlr=new ApplicationController();
        IController LoanProductCtlr=new LoanProductController();

        id Id = ApexPages.currentPage().getParameters().get('Id');
        app = (Application__c)applicationCtlr.getById(Id);
        Loan_Product__c LoanPrd = (Loan_Product__c)LoanProductCtlr.getById(app.Loan_Product__c);
        LoanCalculator calculator = new LoanCalculator();
    
        calculator.calculationMethod = LoanPrd.Interest_Calculation_Method__c;
        calculator.dayCount = LoanPrd.Day_Count__c;


        calculator.repaymentFrequency = app.Repayment_Frequency__c;
        calculator.seasonalPeriods = app.Seasonal_Periods__c;
        calculator.term = app.Term__c;
        calculator.periodsDeferredWithGrace = Integer.valueOf(app.Periods_Deferred_with_Grace__c);
        calculator.Rate = app.Final_Rate__c;
        calculator.balloonAmount = app.Balloon_Amount__c;
        calculator.seasonalPaymentAmount = app.Seasonal_Payment_Amount__c;
        calculator.seasonalInterestPaid = app.Pay_Seasonal_Interest__c;
        calculator.seasonalRepeat = app.Repeat_Seasonal_Periods__c;
        calculator.amount = app.Amount__c;
        calculator.disbursalDate = app.Disbursal_Date__c;
        calculator.initialPaymentDate = app.Initial_Payment_Date__c;
        if (calculator.calculationMethod == 'Compound') {
            calculator.interestCompoundingFrequency = LoanPrd.Interest_Compounding_Frequency__c;
        } else {
            calculator.interestCompoundingFrequency = 'Monthly';
        }

    
        calculator.balloonAmount =
            calculator.balloonAmount == null ? 0 : calculator.balloonAmount;
        calculator.seasonalPaymentAmount =
            calculator.seasonalPaymentAmount == null ? 0 : calculator.seasonalPaymentAmount;
        calculator.periodsDeferredWithGrace =
            calculator.periodsDeferredWithGrace == null ? 0 : calculator.periodsDeferredWithGrace;

        calculator.handleCalculate();
        List <LoanSchedule> loanScheduleList = calculator.loanScheduleList;
        Integer totalCount=loanScheduleList.size();

        scheduledTransactions = new List<Scheduled_Transaction__c>();
        Decimal LastRepaymentNumber = 1;
        for (LoanSchedule loanSchedule: loanScheduleList) {
            Scheduled_Transaction__c scheduledTransaction = new Scheduled_Transaction__c();

           // scheduledTransaction.Loan__c = loanApp.Id;
            if(loanSchedule.type != 'Disbursal'){
            scheduledTransaction.Scheduled_Date__c = loanSchedule.paymentDate;
            scheduledTransaction.Payment_Number__c = LastRepaymentNumber;
            scheduledTransaction.Type__c = loanSchedule.type;
            scheduledTransaction.Principal__c = loanSchedule.principal;
            scheduledTransaction.Interest__c = loanSchedule.interestPaid;
            scheduledTransaction.Fees__c = 0;
            scheduledTransaction.Total_Payment__c = loanSchedule.totalPayment;
            scheduledTransaction.Remaining_Balance__c = LoanSchedule.remainingBalance;
            LastRepaymentNumber++;
            }
            else{
                scheduledTransaction.Principal__c = loanSchedule.principal;
                scheduledTransaction.Remaining_Balance__c = LoanSchedule.remainingBalance;
                scheduledTransaction.Type__c = loanSchedule.type;
                scheduledTransaction.Scheduled_Date__c = loanSchedule.paymentDate;
            }
            scheduledTransactions.add(scheduledTransaction);
        }
      //  Integer val = 1/0;
    }
}