force-app/main/default/objects/Interest_Product__c/Interest_Product__c.object-meta.xml
<CustomObject>
    <label>Interest Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interest_Product__c/fields/Current_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Rate__c</fullName>
    <label>Current Rate</label>
    <precision>9</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Interest_Product__c/fields/Maximum_Rate__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Rate__c</fullName>
    <label>Maximum Rate</label>
    <precision>9</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Interest_Product__c/fields/Minimum_Rate__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Rate__c</fullName>
    <label>Minimum Rate</label>
    <precision>9</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/Loan_Product__c.object-meta.xml
<CustomObject>
    <description>Represents an offered lending product</description>
    <label>Loan Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Product__c/fields/Day_Count__c.field-meta.xml
<CustomField>
    <fullName>Day_Count__c</fullName>
    <description>The method of calculating the number of days in month and year</description>
    <label>Day Count</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Actual / Actual</fullName>
                <default>true</default>
                <label>Actual / Actual</label>
            </value>
            <value>
                <fullName>Actual / 365</fullName>
            </value>
            <value>
                <fullName>Actual / 365.25</fullName>
            </value>
            <value>
                <fullName>Actual / 360</fullName>
            </value>
            <value>
                <fullName>30 / 360</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Default_Amount__c.field-meta.xml
<CustomField>
    <fullName>Default_Amount__c</fullName>
    <label>Default Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Default_Rate__c.field-meta.xml
<CustomField>
    <fullName>Default_Rate__c</fullName>
    <label>Default Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Default_Term__c.field-meta.xml
<CustomField>
    <fullName>Default_Term__c</fullName>
    <label>Default Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Interest_Calculation_Method__c</fullName>
    <label>Interest Calculation Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Simple</fullName>
                <default>true</default>
                <label>Simple</label>
            </value>
            <value>
                <fullName>Compound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Compounding_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Interest_Compounding_Frequency__c</fullName>
    <label>Interest Compounding Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Interest_Calculation_Method__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Interest_Product__c.field-meta.xml
<CustomField>
    <fullName>Interest_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interest Product</label>
    <referenceTo>Interest_Product__c</referenceTo>
    <relationshipName>Loan_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Maximum_Amount__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Maximum Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Maximum_Rate__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Rate__c</fullName>
    <label>Maximum Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Maximum_Term__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Term__c</fullName>
    <description>The maximum number of months the loan can be borrowed for</description>
    <label>Maximum Term</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Minimum_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Minimum Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Minimum_Rate__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Rate__c</fullName>
    <label>Minimum Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Product__c/fields/Minimum_Term__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Term__c</fullName>
    <description>The minimum number of months the loan can be borrowed for</description>
    <label>Minimum Term</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoanProductController.cls
public with sharing class LoanProductController implements IController{

   @AuraEnabled (cacheable=true)
    public static List<SObject> getloanProducts() {
        IController LoanProductController = new LoanProductController();
        List<Loan_Product__c> lPrd = LoanProductController.getAll(null , null );
        return lPrd;
    }
    
    @AuraEnabled (cacheable=true)
    public static SObject getLoanProductCond(string lpName) {
        Id myId = Id.valueOf(lpName); 
        IController LoanProductController = new LoanProductController();
        return LoanProductController.getById(myId);
    }

    public List<SObject> getAll(){
        List<SObject> loanProducts = [SELECT
                Id, Name,                
                Minimum_Amount__c, Maximum_Amount__c, Default_Rate__c,Minimum_Rate__c,Maximum_Rate__c,
                Minimum_Term__c, Maximum_Term__c,Default_Term__c, Default_Amount__c,RecordType.Name,Interest_Product__r.Current_Rate__c,
                Interest_Calculation_Method__c, Day_Count__c, Interest_Compounding_Frequency__c
            FROM Loan_Product__c ORDER BY CreatedDate DESC LIMIT 1000];

        return loanProducts;                        
    }
    public List<SObject> getAll(SObject value){
        return getAll(value,null);
    }
    public List<SObject> getAll(SObject value,String autoNumber){
        Loan_Product__c param;
        if(value == null)
           param = new Loan_Product__c(); 
         else
           param = (Loan_Product__c)Value;
        String queryString = 'SELECT Id, Name,'+
                ' Minimum_Amount__c, Maximum_Amount__c,Minimum_Term__c, Maximum_Term__c,'+
                ' Interest_Calculation_Method__c, Day_Count__c, Interest_Compounding_Frequency__c'+
                ' FROM Loan_Product__c Where';

        if(!string.isBlank(param.Name)){
            queryString += ' Name = \'' + String.escapeSingleQuotes(param.Name) +  '\' AND';
        } 
        if(!string.isBlank(param.Interest_Calculation_Method__c)){
            queryString += ' Interest_Calculation_Method__c = \'' + String.escapeSingleQuotes(param.Interest_Calculation_Method__c) +  '\' AND';
        }  
        if(!string.isBlank(param.Interest_Compounding_Frequency__c)){
            queryString += ' Interest_Compounding_Frequency__c = \'' + String.escapeSingleQuotes(param.Interest_Compounding_Frequency__c) +  '\' AND';
        }          
        if(param.Minimum_Amount__c  != Null){
            queryString += ' Minimum_Amount__c = '+ param.Minimum_Amount__c +' AND';
        }
        if(param.Maximum_Amount__c  != Null){
            queryString += ' Maximum_Amount__c = '+ param.Maximum_Amount__c +' AND';
        }
        if(param.Minimum_Term__c  != Null){
            queryString += ' Minimum_Term__c = '+ param.Minimum_Term__c +' AND';
        }
        if(param.Day_Count__c  != Null){
            queryString += ' Day_Count__c = \'' + String.escapeSingleQuotes( param.Day_Count__c) +  '\' ';
        }
        
        queryString = queryString.removeEnd(' AND');
        queryString = queryString.removeEnd(' Where');
        List<SObject> loanProducts = Database.query(queryString);
        System.debug(loanProducts);

        return loanProducts;
    }

    public SObject getById(Id id){
        SObject LoanProduct = [SELECT Id, Name,                
                Minimum_Amount__c, Maximum_Amount__c,
                Minimum_Term__c, Maximum_Term__c,
                Interest_Calculation_Method__c, Day_Count__c, Interest_Compounding_Frequency__c,RecordTypeId
            FROM Loan_Product__c where id=:id];
        return LoanProduct; 
    }

    public Id create(SObject value){
       // Loan_Product__c LoanProduct =  (Loan_Product__c)value;
        //insert LoanProduct;
        return null;//LoanProduct.id;
    }

    public Boolean createMany(List<SObject> values){
       // List<Loan_Product__c> loanProducts =  (List<Loan_Product__c>)values;
       // insert loanProducts;
        return true;
    }
    public Boolean edit(SObject value){
       // Loan_Product__c LoanProduct =  (Loan_Product__c)value;
       // update LoanProduct;
        return true;
    }

    public Boolean editMany(List<SObject> values){
       // List<Loan_Product__c> loanProducts =  (List<Loan_Product__c>)values;
       // update loanProducts;
        return true;
    }
    public Boolean remove(Id id){
       // Loan_Product__c LoanProduct = [Select Id from Loan_Product__c where id=:id];
       // delete LoanProduct; 
        return true;
    }

}