force-app/main/default/objects/Interest_Product__c/Interest_Product__c.object-meta.xml
<CustomObject>
    <label>Interest Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interest Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interest_Product__c/fields/Current_Rate__c.field-meta.xml
<CustomField>
    <fullName>Current_Rate__c</fullName>
    <label>Current Rate</label>
    <precision>9</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Interest_Product__c/fields/Rate_Last_Changed__c.field-meta.xml
<CustomField>
    <fullName>Rate_Last_Changed__c</fullName>
    <label>Rate Last Changed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestInterestProductController.cls
@IsTest
private with sharing class TestInterestProductController {
    static IController controller = new InterestProductController();
    static IInterestProduct controllerExtention = new InterestProductController();
    static Interest_Product__c interestProduct = new Interest_Product__c();

    static void create(){
        interestProduct.Name = 'testInterestProduct1';
        interestProduct.Current_Rate__c = 5;
        interestProduct.Rate_Last_Changed__c = date.today();
        insert interestProduct;
    }
  
    @IsTest
    static void testCreate(){
        interestProduct.Name = 'testInterestProduct';
        interestProduct.Current_Rate__c = 5;
        Id Id = controller.create(interestProduct);
        System.assertNotEquals(null, Id);
    }
    
    @IsTest
    static void testCreateMany(){
        interestProduct.Name = 'testInterestProduct1';
        interestProduct.Current_Rate__c = 5;

        List<Interest_Product__c> listInterestproduct = new List<Interest_Product__c>(); 
        listInterestproduct.add(interestProduct);

        boolean isTrue = controller.createMany(listInterestproduct);
        System.assertNotEquals(false, isTrue);
    }

    @IsTest
    static void testEdit(){
        create();
        interestProduct.Name = 'testInterestProduct1';
       // interestProduct.Current_Rate__c = 6;

        boolean isTrue = controller.edit(interestProduct);
        System.assertNotEquals(false, isTrue);
    }

    @IsTest
    static void testEditMany(){

        create();

        interestProduct.Name = 'testInterestProduct2';
        List<Interest_Product__c> listInterestproduct = new List<Interest_Product__c>(); 
        listInterestproduct.add(interestProduct);

        boolean isTrue = controller.editMany(listInterestproduct);
        System.assertNotEquals(false, isTrue);
    }

    @IsTest
    static void testGetById(){
        
        create();

        Interest_Product__c interestProduct = (Interest_Product__c)controller.getById(interestProduct.Id);
        System.assertNotEquals(null, interestProduct);

    }

    @IsTest
    static void testGetAll(){
        
        create();

        interestProduct = new Interest_Product__c();
        interestProduct.Name = 'testInterestProduct1';
        interestProduct.Current_Rate__c = 5;
        interestProduct.Active__c =true;
        interestProduct.Rate_Last_Changed__c = date.today();
        interestProduct.OwnerId = UserInfo.getUserId();
        List<Interest_Product__c> interestproducts = (List<Interest_Product__c>)controller.getAll(interestProduct,null);
        Integer resultlength = interestproducts.size();
        System.assertEquals(true, resultlength > 0);

    }
    @IsTest
    static void testCurrentDateUpdate(){
        create();

        Id id = interestProduct.Id;
        controllerExtention.CurrentDateUpdate(id);
    }

    @IsTest
    static void testRemove(){
        create();

        Id id = interestProduct.Id;
        boolean isTrue = controller.remove(id);
        System.assertEquals(true, isTrue);
    }
}