force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Balance_Principal__c.field-meta.xml
<CustomField>
    <fullName>Balance_Principal__c</fullName>
    <label>Balance Principal</label>
    <summarizedField>Loan_Transaction__c.Balance_Principal__c</summarizedField>
    <summaryFilterItems>
        <field>Loan_Transaction__c.Type__c</field>
        <operation>notEqual</operation>
        <value>Recovery</value>
    </summaryFilterItems>
    <summaryForeignKey>Loan_Transaction__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Total_Credit__c.field-meta.xml
<CustomField>
    <fullName>Total_Credit__c</fullName>
    <label>Total Credit</label>
    <summarizedField>Loan_Transaction__c.Total_Credit__c</summarizedField>
    <summaryForeignKey>Loan_Transaction__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Total_Debit__c.field-meta.xml
<CustomField>
    <fullName>Total_Debit__c</fullName>
    <label>Total Debit</label>
    <summarizedField>Loan_Transaction__c.Total_Debit__c</summarizedField>
    <summaryForeignKey>Loan_Transaction__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/Loan_Transaction__c.object-meta.xml
<CustomObject>
    <description>Represents transactions on a related loan record</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TX-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Transaction__c/fields/Balance_Principal__c.field-meta.xml
<CustomField>
    <fullName>Balance_Principal__c</fullName>
    <label>Balance Principal</label>
    <summarizedField>Transaction_Line__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction_Line__c.Type__c</field>
        <operation>equals</operation>
        <value>Principal</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction_Line__c.Transaction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Closing_Balance__c.field-meta.xml
<CustomField>
    <fullName>Closing_Balance__c</fullName>
    <label>Closing Balance</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Created Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Loan_lineNumber__c.field-meta.xml
<CustomField>
    <fullName>Loan_lineNumber__c</fullName>
    <label>Loan_lineNumber</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Total_Credit__c.field-meta.xml
<CustomField>
    <fullName>Total_Credit__c</fullName>
    <label>Total Credit</label>
    <summarizedField>Transaction_Line__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction_Line__c.Amount__c</field>
        <operation>lessThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction_Line__c.Transaction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Total_Debit__c.field-meta.xml
<CustomField>
    <fullName>Total_Debit__c</fullName>
    <label>Total Debit</label>
    <summarizedField>Transaction_Line__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction_Line__c.Amount__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction_Line__c.Transaction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Transaction Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Disbursal</fullName>
            </value>
            <value>
                <fullName>Charge</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Reversal</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Capitalisation</fullName>
            </value>
            <value>
                <fullName>Write Off - Regular</fullName>
            </value>
            <value>
                <fullName>Write Off - Discard</fullName>
            </value>
            <value>
                <fullName>Suspend Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoanTransactionController.cls
public class LoanTransactionController implements IController {
@AuraEnabled
 public static List<SObject> getAll() {
        return
            [SELECT
                Name, CreatedById, Created_Date__c,
                 LastModifiedById, 	Loan_lineNumber__c,Loan__c,
                Transaction_Date__c,Type__c,Total_Credit__c,Total_Debit__c
            FROM Loan_Transaction__c
            ORDER BY CreatedDate DESC
            LIMIT 1000];                       
    }

    @AuraEnabled
    public static List<SObject> getAll(SObject value) {
        return getAll(value, null);
    }

    public static List<SObject> getAll(SObject value, String autoNumber) {
        Loan_Transaction__c param;
        if(value == null)
            param = new Loan_Transaction__c();
        else
           param = (Loan_Transaction__c)value;

        String queryString =
            'SELECT Loan_lineNumber__c , Name, CreatedById,' +
            'Created_Date__c,  LastModifiedById,' +
            'Loan__c, Transaction_Date__c, Type__c,Total_Credit__c,Total_Debit__c,Balance_Principal__c,Closing_Balance__c'+
            ' FROM Loan_Transaction__c WHERE';

        if (!string.isBlank(autoNumber)) {
            queryString += ' Name = \'' + String.escapeSingleQuotes(autoNumber) +  '\' AND';
        }
        if (!string.isBlank(param.Type__c)) {
            queryString += ' Type__c = \'' + String.escapeSingleQuotes(param.Type__c) +  '\' AND';
        }

        if (!string.isBlank(param.Loan__c)) {
            queryString += ' Loan__c = \'' + String.escapeSingleQuotes(param.Loan__c) + '\' AND';
        }

        if (param.Transaction_Date__c != Null) {       
            String formattedDate = DateUtility.formatDateTime(param.Transaction_Date__c, 'yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
            queryString += ' Transaction_Date__c = '+ formattedDate +' AND';
        }

        if (param.Created_Date__c != Null) {       
            String formattedDate = DateUtility.formatDateTime(param.Created_Date__c, 'yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
            queryString += ' Created_Date__c = ' + formattedDate + ' AND';
        }

        if (!string.isBlank(param.Type__c)) {
            queryString += ' Type__c = \'' + String.escapeSingleQuotes(param.Type__c) +  '\'';
        }
        queryString = queryString.removeEnd(' AND');
        queryString = queryString.removeEnd(' WHERE');
		queryString+=' order by CreatedDate desc';
        return Database.query(queryString);
    }

    public static SObject getById(Id id) {
        SObject entity =
            [SELECT 
                Name, CreatedById, Created_Date__c,
                 LastModifiedById, 	Loan_lineNumber__c ,Loan__c,
                Transaction_Date__c,Type__c,Total_Credit__c,Total_Debit__c
            FROM Loan_Transaction__c
            WHERE id=:id];

        return entity; 
    }

    public static Id create(SObject value) {
        //Loan_Transaction__c entity = (Loan_Transaction__c)value;
        //insert entity;
        return null; //entity.id;
    }

    public static Boolean createMany(List<SObject> values) {
        //List<Loan_Transaction__c> entities = (List<Loan_Transaction__c>)values;
       // insert entities;
        return true;
    }

    public static Boolean edit(SObject value) {
        //Loan_Transaction__c entity = (Loan_Transaction__c)value;
       // update entity;
        return true;
    }

    public static Boolean editMany(List<SObject> values) {
       // List<Loan_Transaction__c> entity = (List<Loan_Transaction__c>)values;
        //update entity;
        return true;
    }

    public static Boolean remove(Id id) {
       // Loan_Transaction__c entity = [SELECT Id FROM Loan_Transaction__c WHERE Id=:id];
       // delete entity; 
        return true;
    }
}