force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Approved Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Balance_Interest__c.field-meta.xml
<CustomField>
    <fullName>Balance_Interest__c</fullName>
    <label>Balance Interest</label>
    <summarizedField>Loan_Transaction__c.Balance_Interest__c</summarizedField>
    <summaryFilterItems>
        <field>Loan_Transaction__c.Type__c</field>
        <operation>notEqual</operation>
        <value>Recovery</value>
    </summaryFilterItems>
    <summaryForeignKey>Loan_Transaction__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Balance_Principal__c.field-meta.xml
<CustomField>
    <fullName>Balance_Principal__c</fullName>
    <label>Balance Principal</label>
    <summarizedField>Loan_Transaction__c.Balance_Principal__c</summarizedField>
    <summaryFilterItems>
        <field>Loan_Transaction__c.Type__c</field>
        <operation>notEqual</operation>
        <value>Recovery</value>
    </summaryFilterItems>
    <summaryForeignKey>Loan_Transaction__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Total_Credit__c.field-meta.xml
<CustomField>
    <fullName>Total_Credit__c</fullName>
    <label>Total Credit</label>
    <summarizedField>Loan_Transaction__c.Total_Credit__c</summarizedField>
    <summaryForeignKey>Loan_Transaction__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Total_Debit__c.field-meta.xml
<CustomField>
    <fullName>Total_Debit__c</fullName>
    <label>Total Debit</label>
    <summarizedField>Loan_Transaction__c.Total_Debit__c</summarizedField>
    <summaryForeignKey>Loan_Transaction__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/Loan_Transaction__c.object-meta.xml
<CustomObject>
    <description>Represents transactions on a related loan record</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TX-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Transaction_Line__c.Amount__c</summarizedField>
    <summaryForeignKey>Transaction_Line__c.Transaction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Amount_P__c.field-meta.xml
<CustomField>
    <fullName>Amount_P__c</fullName>
    <formula>IF ( Amount__c &lt; 0 ,  -1 *  Amount__c  , Amount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount_P</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Balance_Interest__c.field-meta.xml
<CustomField>
    <fullName>Balance_Interest__c</fullName>
    <label>Balance Interest</label>
    <summarizedField>Transaction_Line__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction_Line__c.Type__c</field>
        <operation>equals</operation>
        <value>Interest</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction_Line__c.Transaction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Balance_Principal__c.field-meta.xml
<CustomField>
    <fullName>Balance_Principal__c</fullName>
    <label>Balance Principal</label>
    <summarizedField>Transaction_Line__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction_Line__c.Type__c</field>
        <operation>equals</operation>
        <value>Principal</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction_Line__c.Transaction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Closing_Balance__c.field-meta.xml
<CustomField>
    <fullName>Closing_Balance__c</fullName>
    <label>Closing Balance</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Closing_Interest__c.field-meta.xml
<CustomField>
    <fullName>Closing_Interest__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Closing_Principal__c.field-meta.xml
<CustomField>
    <fullName>Closing_Principal__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Principal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Loan_lineNumber__c.field-meta.xml
<CustomField>
    <fullName>Loan_lineNumber__c</fullName>
    <label>Loan_lineNumber</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
                <default>true</default>
                <label>Bank Transfer</label>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Total_Credit__c.field-meta.xml
<CustomField>
    <fullName>Total_Credit__c</fullName>
    <label>Total Credit</label>
    <summarizedField>Transaction_Line__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction_Line__c.Amount__c</field>
        <operation>lessThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction_Line__c.Transaction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Total_Debit__c.field-meta.xml
<CustomField>
    <fullName>Total_Debit__c</fullName>
    <label>Total Debit</label>
    <summarizedField>Transaction_Line__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Transaction_Line__c.Amount__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>Transaction_Line__c.Transaction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Transaction Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Disbursal</fullName>
            </value>
            <value>
                <fullName>Charge</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Reversal</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Capitalisation</fullName>
            </value>
            <value>
                <fullName>Write Off - Regular</fullName>
            </value>
            <value>
                <fullName>Write Off - Discard</fullName>
            </value>
            <value>
                <fullName>Suspend Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Line__c/Transaction_Line__c.object-meta.xml
<CustomObject>
    <label>Transaction Line</label>
    <nameField>
        <displayFormat>TL-{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Line__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee</label>
    <referenceTo>Fee__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Line__c/fields/get_fee_name__c.field-meta.xml
<CustomField>
    <fullName>get_fee_name__c</fullName>
    <formula>IF( ISPICKVAL( Type__c  , &apos;Fee&apos;), &quot;Fee: &quot; &amp;Fee__r.Name ,
IF( ISPICKVAL( Type__c , &apos;Interest&apos;) , TEXT(Type__c ) ,
IF( ISPICKVAL( Type__c , &apos;Principal&apos;) , TEXT(Type__c ),
IF( ISPICKVAL( Type__c , &apos;Interest Accrued&apos;) , TEXT(Type__c ),
&apos;&apos;
))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>get fee name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Line__c/fields/Total_Credit__c.field-meta.xml
<CustomField>
    <fullName>Total_Credit__c</fullName>
    <formula>IF(Amount__c&lt;0,(-1)*Amount__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Line__c/fields/Total_Debit__c.field-meta.xml
<CustomField>
    <fullName>Total_Debit__c</fullName>
    <formula>IF(Amount__c&gt;0,Amount__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Debit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Line__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Loan_Transaction__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction_Line__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Interest Accrued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WriteOff__c/WriteOff__c.object-meta.xml
<CustomObject>
    <label>WriteOff</label>
    <nameField>
        <displayFormat>WOF-{000000}</displayFormat>
        <label>WriteOff Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WriteOff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WriteOff__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WriteOff__c/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WriteOff__c/fields/Principal__c.field-meta.xml
<CustomField>
    <fullName>Principal__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Principal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WriteOff__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionLineController.cls
public with sharing class TransactionLineController implements ITransactionLine {
  
    @AuraEnabled
    public static List<SObject> getAllRelatedLoan(Id id) {
        return getAllRelatedLoan(id,1000,0);
    }
    
    @AuraEnabled
    public static List<SObject> getAllRelatedByLimit(Id id,Integer lim) {
        return getAllRelatedLoan(id,lim,0);
    }
    
    @AuraEnabled
    public static List<SObject> getAllRelatedByDay(Id id,Integer days) {
        return getAllRelatedLoan(id,1000,days);
    }
    
    public static List<SObject> getAllRelatedLoan(Id id, Integer lim, Integer days){
        String queryString='SELECT Id, Loan_lineNumber__c , Type__c, Amount_P__c , Total_Credit__c, Total_Debit__c, Balance_Principal__c ,'+
            				' Balance_Interest__c , Closing_Balance__c, Transaction_Date__c,Closing_Principal__c,Closing_Interest__c, '+ 
            				' Name, Note__c, Payment_Method__c , CreatedById,'+
                           ' (SELECT Id, Amount__c,Fee__c,get_fee_name__c,Type__c FROM Transaction_Lines__r)'+
                           ' FROM Loan_Transaction__c WHERE';

        if (!string.isBlank(id)) {
            queryString += ' Loan__c = \'' + String.escapeSingleQuotes(Id) +  '\' AND';
        }
      
        if (days != 0) {
            
            List<Loan_Transaction__c> lastTransaction = [Select Transaction_Date__c from Loan_Transaction__c where Loan__c=:id Order by Transaction_Date__c desc Limit 1 ];
            if(lastTransaction.size()>0){
            DateTime lastTransactionDate = lastTransaction[0].Transaction_Date__c;
            DateTime limtedDate = lastTransactionDate.addDays((-1)*days);
            queryString += ' Transaction_Date__c >=: limtedDate and Transaction_Date__c <=:  lastTransactionDate ';
            }
        }
      
        queryString = queryString.removeEnd(' AND');
        queryString += ' ORDER BY Name DESC LIMIT ' + lim;
        
        return Database.query(queryString);
    }
    
    @InvocableMethod(label='Get Writeoff amount sum')
    public static List<writeoffSummaryResult>  getWriteoffSum(List<Id> loanId){
		//List<AggregateResult> amount = [select sum(Balance_Principal__c), sum(Balance_Interest__c), sum(Balance_Fees__c) 
                                        //from Loan_Transaction__c 
                                        //where Type__c LIKE '%Write Off - %' and Loan__c =: loanId[0]];
        List<AggregateResult> aggregate = [select sum(Principal__c) principal, sum(Interest__c) interest, sum(Fee__c) fee 
                                        from Writeoff__c
                                        where Loan__c =: loanId[0]];
        
        List<writeoffSummaryResult> res = new List<writeoffSummaryResult>();
        writeoffSummaryResult k = new writeoffSummaryResult();
        k.principalAmt = (Decimal) aggregate[0].get('principal');
        k.interestAmt = (Decimal) aggregate[0].get('interest');
		k.feesAmt = (Decimal) aggregate[0].get('fee');
        res.add(k);
      	return res;
    }
}