force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Approved Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/Loan_Transaction__c.object-meta.xml
<CustomObject>
    <description>Represents transactions on a related loan record</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TX-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>Transaction_Line__c.Amount__c</summarizedField>
    <summaryForeignKey>Transaction_Line__c.Transaction__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Closing_Balance__c.field-meta.xml
<CustomField>
    <fullName>Closing_Balance__c</fullName>
    <label>Closing Balance</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Created Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Loan_lineNumber__c.field-meta.xml
<CustomField>
    <fullName>Loan_lineNumber__c</fullName>
    <label>Loan_lineNumber</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Transaction Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Loan_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
                <default>true</default>
                <label>Payment</label>
            </value>
            <value>
                <fullName>Disbursal</fullName>
            </value>
            <value>
                <fullName>Charge</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Reversal</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Capitalisation</fullName>
            </value>
            <value>
                <fullName>Write Off - Regular</fullName>
            </value>
            <value>
                <fullName>Write Off - Discard</fullName>
            </value>
            <value>
                <fullName>Suspend Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Line__c/Transaction_Line__c.object-meta.xml
<CustomObject>
    <label>Transaction Line</label>
    <nameField>
        <displayFormat>TL-{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Line__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Loan_Transaction__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction_Line__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Interest Accrued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WriteOff__c/WriteOff__c.object-meta.xml
<CustomObject>
    <label>WriteOff</label>
    <nameField>
        <displayFormat>WOF-{000000}</displayFormat>
        <label>WriteOff Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WriteOff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WriteOff__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>WriteOff</relationshipLabel>
    <relationshipName>WriteOff</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WriteOff__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Loan_Transaction__c</referenceTo>
    <relationshipLabel>WriteOff</relationshipLabel>
    <relationshipName>WriteOff</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WriteOff__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestTransactionLineController.cls
@IsTest
private with sharing class TestTransactionLineController {
	static ITransactionLine controller = new TransactionLineController();
    static SampleDataObjects dataSet = new SampleDataObjects();
    
    static Transaction_Line__c tl = new Transaction_Line__c();
    static WriteOff__c wf = new WriteOff__c();
    
    @IsTest
    static void getAll(){
        List<Loan_Transaction__c> tlList = new List<Loan_Transaction__c>();
        
        tl = (Transaction_Line__c) dataSet.createTransactionLine('Contact','Simple');
		Loan_Transaction__c tr = [select Loan__c from Loan_Transaction__c where Id =: tl.Transaction__c];
        
        Integer resultlength ;
        tlList = (List<Loan_Transaction__c>)controller.getAllRelatedLoan(tr.Loan__c);
        resultlength = tlList.size();
        System.assertEquals(true, resultlength > 0);
        
        tlList = (List<Loan_Transaction__c>)controller.getAllRelatedByLimit(tr.Loan__c,1);
        resultlength = tlList.size();
        System.assertEquals(true, resultlength > 0);
        
        tlList = (List<Loan_Transaction__c>)controller.getAllRelatedByDay(tr.Loan__c,1);
        resultlength = tlList.size();
        System.assertEquals(true, resultlength > 0);
        
        Loan_Transaction__c tr1 =  new Loan_Transaction__c();
        tr1.Closing_Balance__c = 100;
        tr1.Type__c = 'Disbursal';
        tr1.Created_Date__c = date.today();
        tr1.Loan_lineNumber__c = 2;
        tr1.Loan__c = tr.Loan__c;
        tr1.Transaction_Date__c = date.today();
        insert tr1;
        
        Transaction_Line__c tl1 = new Transaction_Line__c();
        tl1.Transaction__c = tr1.Id;
        tl1.Type__c = 'Principal';
        tl1.Amount__c = 100;
        insert tl1;
    }
    
    @IsTest
    static void getWriteoffSum(){
        wf = (WriteOff__c) dataSet.createWriteOff('Contact','Simple');
        List<Id> ids = new List<Id>{wf.Loan__c};
        List<writeoffSummaryResult> res = TransactionLineController.getWriteoffSum(ids);
        System.assertNotEquals(null, res);
    }
    
    @IsTest
    static void forLineCoverage(){
        tl = (Transaction_Line__c) dataSet.createTransactionLine('Contact','Compound');
    }
}