force-app/main/default/objects/Risk_Rating__c/Risk_Rating__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <displayFormat>RIS-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Rating__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Risk Ratings</relationshipLabel>
    <relationshipName>Risk_Ratings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Risk_Rating__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Rating__c/fields/Risk_Rating__c.field-meta.xml
<CustomField>
    <fullName>Risk_Rating__c</fullName>
    <label>Risk Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Rating_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Risk_Rating_Options.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Very Low</fullName>
    </customValue>
    <customValue>
        <fullName>Low</fullName>
    </customValue>
    <customValue>
        <fullName>Medium</fullName>
    </customValue>
    <customValue>
        <fullName>High</fullName>
    </customValue>
    <customValue>
        <fullName>Very High</fullName>
    </customValue>
    <masterLabel>Risk Rating Options</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestRiskRatingController.cls
@IsTest
private with sharing class TestRiskRatingController {
	static IController controller = new RiskRatingController();
    static RiskRatingController ctrl = new RiskRatingController();
    static SampleDataObjects dataSet = new SampleDataObjects();

    static Risk_Rating__c risk = new Risk_Rating__c();
	
    @IsTest
    static void testCreate(){
        Id Id = controller.create(null);
        System.assertEquals(null, Id);
    }
    
    @IsTest
    static void testCreateMany(){
		risk = (Risk_Rating__c) dataSet.createRiskRating();
        Risk_Rating__c rt = new Risk_Rating__c(Category__c = 'test', Account__c = risk.Account__c);
        List<Risk_Rating__c> rsList  = new List<Risk_Rating__c>();
        rsList.add(rt);
        boolean isTrue = controller.createMany(rsList);
        System.assertNotEquals(false, isTrue);
    }

    @IsTest
    static void testEdit(){
        boolean isTrue = controller.edit(risk);
        System.assertNotEquals(false, isTrue);
    }

    @IsTest
    static void testEditMany(){
        boolean isTrue = controller.editMany(null);
        System.assertNotEquals(false, isTrue);
    }

    @IsTest
    static void testGetById(){
        Risk_Rating__c orisk = (Risk_Rating__c)controller.getById(risk.Id);
        System.assertEquals(null, orisk);

    }

    @IsTest
    static void testGetAll(){
        List<Risk_Rating__c> risks = new List<Risk_Rating__c>();
        
        Integer resultlength ;
        
        risk = (Risk_Rating__c) dataSet.createRiskRating();
        risks = (List<Risk_Rating__c>)controller.getAll(risk,'RIS-000000');
        resultlength = risks.size();
        System.assertNotEquals(true, resultlength > 0);
        
        risks = (List<Risk_Rating__c>)RiskRatingController.getAll();
        resultlength = risks.size();
        System.assertEquals(true, resultlength>0);
        
        risks = (List<Risk_Rating__c>)RiskRatingController.getAll(null);
        resultlength = risks.size();
        System.assertEquals(true, resultlength>0);
    }

    @IsTest
    static void testRemove(){
        boolean isTrue = controller.remove(null);
        System.assertEquals(true, isTrue);
    }

}