force-app/main/default/objects/Risk_Rating__c/Risk_Rating__c.object-meta.xml
<CustomObject>
    <label>Risk Rating</label>
    <nameField>
        <displayFormat>RIS-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Rating__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Risk Ratings</relationshipLabel>
    <relationshipName>Risk_Ratings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Risk_Rating__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Rating__c/fields/Category_Weight__c.field-meta.xml
<CustomField>
    <fullName>Category_Weight__c</fullName>
    <formula>CASE( Category__c ,
  &apos;Management&apos;, 15,
  &apos;Age of Business&apos;, 10,
  &apos;Market&apos;, 10,
  &apos;Credit History&apos;,10,
  &apos;Capacity of the Owners (Staying Power)&apos;,5,
  &apos;Home Ownership&apos;,5,
  &apos;Financial Debt Leverage&apos;,5,
  &apos;Working Capital&apos;,5,
  &apos;Repayment Ability&apos;,15,
  &apos;Security&apos;,15,
  &apos;Industry&apos;,5,
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Risk_Rating__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <formula>CASE( Risk_Rating__c , 
   &apos;Very Low&apos;, 1, 
   &apos;Low&apos;, 2,
   &apos;Medium&apos;,3,
   &apos;High&apos;,4,
   &apos;Very High&apos;,5,
0) *  Category_Weight__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Risk_Rating__c/fields/Rationale__c.field-meta.xml
<CustomField>
    <fullName>Rationale__c</fullName>
    <label>Rationale</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Risk_Rating__c/fields/Risk_Rating__c.field-meta.xml
<CustomField>
    <fullName>Risk_Rating__c</fullName>
    <label>Risk Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Risk_Rating_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Risk_Rating_Options.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Very Low</fullName>
    </customValue>
    <customValue>
        <fullName>Low</fullName>
    </customValue>
    <customValue>
        <fullName>Medium</fullName>
    </customValue>
    <customValue>
        <fullName>High</fullName>
    </customValue>
    <customValue>
        <fullName>Very High</fullName>
    </customValue>
    <masterLabel>Risk Rating Options</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RiskRatingController.cls
public class RiskRatingController implements IController{
	@AuraEnabled
    public static List<SObject> getAll(){
        return [SELECT
                     Name, Account__c, Category__c, Category_Weight__c, Risk_Rating__c,Rationale__c, Rating__c	
                FROM Risk_Rating__c	
                ORDER BY CreatedDate DESC
                LIMIT 1000];                         
    }
    @AuraEnabled
    public static List<SObject> getAll(SObject value) {
        return getAll(value, null);
    }
    public static List<SObject> getAll(SObject value,String autoNumber){
        Risk_Rating__c param;
        if(value == null)
            param = new Risk_Rating__c();
        else
            param = (Risk_Rating__c)Value;
        String queryString = 'Select Name,  Account__c, Category__c, Category_Weight__c, Risk_Rating__c,Rationale__c, Rating__c from Risk_Rating__c where';

        if(!string.isBlank(autoNumber)){
            queryString += ' Name = \'' + String.escapeSingleQuotes(autoNumber) +  '\' AND';
        }
        
        if (!string.isBlank(param.Account__c)) {
            queryString += ' Account__c   = \'' + String.escapeSingleQuotes(param.Account__c) + '\' AND';
        }
       
        if (!string.isBlank(param.Category__c)) {
            queryString += ' Category__c   = \'' + String.escapeSingleQuotes(param.Category__c) + '\' AND';
        }
        
        queryString = queryString.removeEnd(' AND');
        queryString = queryString.removeEnd(' where');

        return Database.query(queryString);
    }

    @AuraEnabled
    public static SObject getById(Id id){
        /*SObject entity = [SELECT Name, Account__c, Category__c, Category_Weight__c, Risk_Rating__c,Rationale__c,Rating__c
                        FROM Risk_Rating__c
                        WHERE Id=:id];*/
        return null;// entity; 
    }

    public Id create(SObject value) {
        //Risk_Rating__c entity = (Risk_Rating__c)value;
        return null;// entity.Id;
    }

    public Boolean createMany(List<SObject> values) {
        List<Risk_Rating__c> entities = (List<Risk_Rating__c>)values;
        insert entities;
        return true;
    }

    public Boolean edit(SObject value) {
        //Risk_Rating__c entity = (Risk_Rating__c)value;
       // update entity;
        return true;
    }

    public Boolean editMany(List<SObject> values) {
       // List<Risk_Rating__c> entities = (List<Risk_Rating__c>)values;
        //update entities;
        return true;
    }

    public Boolean remove(Id id) {
       // Risk_Rating__c entity = [SELECT Id FROM Risk_Rating__c WHERE Id=:id];
       // delete entity; 
        return true;
    }
}