force-app/main/default/objects/Line_of_Credit__c/Line_of_Credit__c.object-meta.xml
<CustomObject>
    <label>Line of Credit</label>
    <nameField>
        <displayFormat>LOC-{000000}</displayFormat>
        <label>Line of Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lines of Credit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_of_Credit_Transaction__c/Line_of_Credit_Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TX-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_of_Credit_Transaction__c/fields/Line_of_Credit__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Credit__c</fullName>
    <label>Line of Credit</label>
    <referenceTo>Line_of_Credit__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_of_Credit_Transaction__c/fields/Reversed_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Reversed_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reversed Transaction</label>
    <referenceTo>Line_of_Credit_Transaction__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_of_Credit_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Charge</fullName>
            </value>
            <value>
                <fullName>Reversal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Line_of_Credit_Transaction_Line__c/Line_of_Credit_Transaction_Line__c.object-meta.xml
<CustomObject>
    <label>Transaction Line</label>
    <nameField>
        <displayFormat>TL-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_of_Credit_Transaction_Line__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Line_of_Credit_Transaction_Line__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Line_of_Credit_Transaction__c</referenceTo>
    <relationshipLabel>Transaction Lines</relationshipLabel>
    <relationshipName>Transaction_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Line_of_Credit_Transaction_Line__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoCTransactionController.cls
public class LoCTransactionController implements IController {
     @AuraEnabled
    public static List<SObject> getAll(){
             return [SELECT
                    Name, Type__c,Line_of_Credit__c, Transaction_Date__c,Reversed__c, Reversed_Transaction__c, 
                (SELECT Id, Amount__c, Type__c,Description__c FROM Transaction_Lines__r) 
                FROM Line_of_Credit_Transaction__c	
                ORDER BY CreatedDate DESC
                LIMIT 1000];           

    }
    @AuraEnabled
    public static List<SObject> getAll(SObject value) {
        return getAll(value, null);
    }
    public static List<SObject> getAll(SObject value,String autoNumber){
        Line_of_Credit_Transaction__c param = (Line_of_Credit_Transaction__c)Value;
        String queryString = 'Select Name, Type__c, Line_of_Credit__c, Transaction_Date__c,Reversed__c, Reversed_Transaction__c,'+
            				'     (SELECT Id, Amount__c, Type__c,Description__c FROM Transaction_Lines__r) '+
            					' FROM Line_of_Credit_Transaction__c where';

        if(!string.isBlank(autoNumber)){
            queryString += ' Name = \'' + String.escapeSingleQuotes(autoNumber) +  '\' AND';
        }
       
        if (!string.isBlank(param.Type__c)) {
            queryString += 'Type__c   = \'' + String.escapeSingleQuotes(param.Type__c) + '\' AND';
            
        }  if (!string.isBlank(param.Line_of_Credit__c)) {
            queryString += ' Line_of_Credit__c = \'' + String.escapeSingleQuotes(param.Line_of_Credit__c) + '\' AND';
        }
         if(param.get('Reversed__c') != Null){
        	queryString += ' Reversed__c = '+ param.Reversed__c;
        }
        
            
        queryString = queryString.removeEnd(' AND');
		queryString += ' ORDER BY Name desc';
        
        return Database.query(queryString);
    }

    @AuraEnabled
    public static SObject getById(Id id){
        SObject entity = [SELECT 
                      Name, Type__c, Line_of_Credit__c, Transaction_Date__c,Reversed__c, Reversed_Transaction__c,
                  (SELECT Id, Amount__c, Type__c,Description__c FROM Transaction_Lines__r) 
                        FROM Line_of_Credit_Transaction__c
                        WHERE Id=:id];
        return entity; 
    }

    public Id create(SObject value) {
        Line_of_Credit_Transaction__c entity = (Line_of_Credit_Transaction__c)value;
        return entity.Id;
    }

    public Boolean createMany(List<SObject> values) {
        List<Line_of_Credit_Transaction__c> entities = (List<Line_of_Credit_Transaction__c>)values;
        insert entities;
        return true;
    }

    public Boolean edit(SObject value) {
        Line_of_Credit_Transaction__c entity = (Line_of_Credit_Transaction__c)value;
        update entity;
        return true;
    }

    public Boolean editMany(List<SObject> values) {
        List<Line_of_Credit_Transaction__c> entities = (List<Line_of_Credit_Transaction__c>)values;
        update entities;
        return true;
    }

    public Boolean remove(Id id) {
        Line_of_Credit_Transaction__c entity = [SELECT Id FROM Line_of_Credit_Transaction__c WHERE Id=:id];
        delete entity; 
        return true;
    }

}