force-app/main/default/objects/Savings_Account__c/Savings_Account__c.object-meta.xml
<CustomObject>
    <label>Savings Account</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Savings Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Savings_Product_Transaction__c/Savings_Product_Transaction__c.object-meta.xml
<CustomObject>
    <label>Savings Product Transaction</label>
    <nameField>
        <displayFormat>TX-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Savings Product Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Savings_Product_Transaction__c/fields/Reversed__c.field-meta.xml
<CustomField>
    <fullName>Reversed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reversed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Savings_Product_Transaction__c/fields/Reversed_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Reversed_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reversed Transaction</label>
    <referenceTo>Savings_Product_Transaction__c</referenceTo>
    <relationshipLabel>Savings Product Transactions</relationshipLabel>
    <relationshipName>Reversed_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Savings_Product_Transaction__c/fields/Savings_Account__c.field-meta.xml
<CustomField>
    <fullName>Savings_Account__c</fullName>
    <label>Savings Account</label>
    <referenceTo>Savings_Account__c</referenceTo>
    <relationshipLabel>Savings Product Transactions</relationshipLabel>
    <relationshipName>Savings_Product_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Savings_Product_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Reversal</fullName>
            </value>
            <value>
                <fullName>Charge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Savings_Product_Transaction_Line__c/Savings_Product_Transaction_Line__c.object-meta.xml
<CustomObject>
    <label>Savings Product Transaction Line</label>
    <nameField>
        <displayFormat>SP-TX-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Savings Product Transaction Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Savings_Product_Transaction_Line__c/fields/Savings_Product_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Savings_Product_Transaction__c</fullName>
    <label>Savings Product Transaction</label>
    <referenceTo>Savings_Product_Transaction__c</referenceTo>
    <relationshipName>Savings_Transaction_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Savings_Product_Transaction_Line__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SavingsProductTransactionController.cls
public class SavingsProductTransactionController implements IController{
 @AuraEnabled
    public static List<SObject> getAll(){
        return [SELECT
                    Name, Type__c, Savings_Account__c, Transaction_Date__c, Reversed__c, Reversed_Transaction__c, 
                (SELECT Id, Amount__c, Type__c, Description__c FROM Savings_Transaction_Lines__r) 
                FROM Savings_Product_Transaction__c	
                ORDER BY CreatedDate DESC
                LIMIT 1000];                         
    }
    @AuraEnabled
    public static List<SObject> getAll(SObject value) {
        return getAll(value, null);
    }
    public static List<SObject> getAll(SObject value,String autoNumber){
        Savings_Product_Transaction__c param = (Savings_Product_Transaction__c)Value;
        String queryString = 'Select Name, Type__c, Savings_Account__c, Transaction_Date__c, Reversed__c, Reversed_Transaction__c,'+
            				' (Select Id, Amount__c, Type__c, Description__c FROM Savings_Transaction_Lines__r)'+
            					' FROM Savings_Product_Transaction__c where';

        if(!string.isBlank(autoNumber)){
            queryString += ' Name = \'' + String.escapeSingleQuotes(autoNumber) +  '\' AND';
        }
       
        if (!string.isBlank(param.Type__c)) {
            queryString += 'Type__c   = \'' + String.escapeSingleQuotes(param.Type__c) + '\' AND';
        }
        
        if (!string.isBlank(param.Savings_Account__c)) {
            queryString += ' Savings_Account__c = \'' + String.escapeSingleQuotes(param.Savings_Account__c) + '\' AND';
        }

        if(param.get('Reversed__c') != Null){
        	queryString += ' Reversed__c = '+ param.Reversed__c;
        }
        
        queryString = queryString.removeEnd(' AND');
		queryString += ' ORDER BY Name desc';
        
        return Database.query(queryString);
    }

    @AuraEnabled
    public static SObject getById(Id id){
        SObject entity = [SELECT 
                          Name, Type__c, Savings_Account__c, Transaction_Date__c, Reversed__c, Reversed_Transaction__c,
                          (SELECT Id, Amount__c, Type__c, Description__c FROM Savings_Transaction_Lines__r)
                        FROM Savings_Product_Transaction__c
                        WHERE Id=:id];
        return entity; 
    }

    public Id create(SObject value) {
        Savings_Product_Transaction__c entity = (Savings_Product_Transaction__c)value;
        return entity.Id;
    }

    public Boolean createMany(List<SObject> values) {
        List<Savings_Product_Transaction__c> entities = (List<Savings_Product_Transaction__c>)values;
        insert entities;
        return true;
    }

    public Boolean edit(SObject value) {
        Savings_Product_Transaction__c entity = (Savings_Product_Transaction__c)value;
        update entity;
        return true;
    }

    public Boolean editMany(List<SObject> values) {
        List<Savings_Product_Transaction__c> entities = (List<Savings_Product_Transaction__c>)values;
        update entities;
        return true;
    }

    public Boolean remove(Id id) {
        Savings_Product_Transaction__c entity = [SELECT Id FROM Savings_Product_Transaction__c WHERE Id=:id];
        delete entity; 
        return true;
    }
}